language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.4/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
install:
- git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
- cd org.geppetto.model
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
- cd org.geppetto.core
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git -b $TRAVIS_BRANCH
- cd org.geppetto.simulation
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git -b $TRAVIS_BRANCH
- cd org.geppetto.model.neuroml
- mvn install
- cd ..
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz
- tar xzvf nrn-7.4.tar.gz
- cd nrn-7.4
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ..
- cd ..
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulator.external.git -b $TRAVIS_BRANCH
- cd org.geppetto.simulator.external
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulator.scidash.git -b $TRAVIS_BRANCH
- cd org.geppetto.simulator.scidash
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.swc.git -b $TRAVIS_BRANCH
- cd org.geppetto.model.swc
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.persistence.git -b $TRAVIS_BRANCH
- cd org.geppetto.persistence
- mvn install
- cd ..
