language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.3/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=

install:
- git clone https://github.com/openworm/org.geppetto.model.git --quiet -b development
- cd org.geppetto.model
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git --quiet -b development
- cd org.geppetto.core
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git --quiet -b development
- cd org.geppetto.simulation
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git --quiet -b development
- cd org.geppetto.model.neuroml
- mvn --quiet -q install
- cd ..
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.3/nrn-7.3.tar.gz
- tar xzvf nrn-7.3.tar.gz
- cd nrn-7.3
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ..
- cd ..
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulator.external.git --quiet -b development
- cd org.geppetto.simulator.external
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.swc.git --quiet -b development
- cd org.geppetto.model.swc
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.persistence.git --quiet -b development
- cd org.geppetto.persistence
- mvn --quiet -q install
- cd ..
- npm install --silent -g phantomjs npm install --silent -g casperjs npm install --silent -g slimerjs

sudo: required

services:
  - docker
  
script:
  - docker build -t="geppetto" https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto/
  - docker run  -t -dit --name=geppetto_container -p  8080:8080 geppetto
  - docker build -t="geppetto_casper" https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto-casperjs/
  - docker run  -t -it --name=geppetto_casper_container geppetto_casper
  - docker stop $(docker ps -a -q)