language: node_js
os: linux
sudo: required
dist: trusty
node_js:
  - "7"
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.4/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
install:
- git clone https://github.com/openworm/org.geppetto.model.git --quiet -b development
- cd org.geppetto.model
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git --quiet -b development
- cd org.geppetto.core
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git --quiet -b development
- cd org.geppetto.simulation
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git --quiet -b development
- cd org.geppetto.model.neuroml
- mvn --quiet -q install
- cd ..
- wget -q http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz
- tar xzf nrn-7.4.tar.gz
- cd nrn-7.4
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make -s
- make -s install
- cd src/nrnpython
- sudo python setup.py install
- cd ..
- cd ..
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.swc.git --quiet -b development
- cd org.geppetto.model.swc
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.frontend.git --quiet -b change_casperjs_port
- cd org.geppetto.frontend
- mvn --quiet -q install
- cd ..
- npm install --silent -g phantomjs 
- npm install --silent -g casperjs 
- npm install --silent -g slimerjs
- sudo apt-get install -qq -y libc6 libstdc++6 libgcc1 libgtk2.0-0 libasound2 libxrender1 libdbus-glib-1-2
- sudo apt-get install -qq -y libgtk-3-dev lshw
- sudo apt-get install -qq -y build-essential libxi-dev libglu1-mesa-dev libglew-dev
- npm install --silent -g gl

services:
  - docker
addons:
  firefox: "51.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-51.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    
script:
  - cd org.geppetto.frontend/src/main/webapp/js/pages/tests/casperjs
  - docker build -t="geppetto" https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto/
  - docker run  -t -dit --name=geppetto_container -h localhost -p  28081:8080 geppetto
  - chmod +x $TRAVIS_BUILD_DIR/test_geppetto_server.sh
  - bash $TRAVIS_BUILD_DIR/test_geppetto_server.sh
  - sleep 60
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test --includes=CoreTestsUtility.js CoreTests.js --host=http://localhost:28081/ --engine=slimerjs
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker build -t="geppetto_persistence" --build-arg aKey=$accessKey --build-arg sKey=$secretKey https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto-persistence/
  - docker run  -t -dit --name=geppetto_persistence_container -h localhost -p 28081:8080 geppetto_persistence
  - bash $TRAVIS_BUILD_DIR/test_geppetto_server.sh
  - sleep 60
  - xvfb-run -a --server-args="-screen 0 1024x768x24" casperjs test PersistenceTests.js --host=http://localhost:28081/ --engine=slimerjs
  - sudo docker cp geppetto_persistence_container:/home/developer/virgo/serviceability/logs/log.log /etc