language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.3/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=

sudo: required

services:
  - docker
  
script:
  - docker build https://github.com/openworm/org.geppetto.git#master:utilities/docker/geppetto/
  - docker build https://github.com/openworm/org.geppetto.git#master:utilities/docker/geppetto-persistence
  - docker logs test
  - curl -sSf http://localhost:80/index.html