language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.3/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=

install:
- git clone https://github.com/openworm/org.geppetto.model.git -b development
- cd org.geppetto.model
- mvn install --quiet -q
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git -b development
- cd org.geppetto.core
- mvn install --quiet -q
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git -b development
- cd org.geppetto.simulation
- mvn install --quiet -q
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git -b development
- cd org.geppetto.model.neuroml
- mvn install --quiet -q
- cd ..
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.3/nrn-7.3.tar.gz
- tar xzvf nrn-7.3.tar.gz
- cd nrn-7.3
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ..
- cd ..
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulator.external.git -b development
- cd org.geppetto.simulator.external
- mvn install --quiet -q
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.swc.git -b development
- cd org.geppetto.model.swc
- mvn install --quiet -q
- cd ..
- git clone https://github.com/openworm/org.geppetto.persistence.git -b development
- cd org.geppetto.persistence
- mvn install --quiet -q
- cd ..
- npm install -g phantomjs npm install -g casperjs npm install -g slimerjs

sudo: required

services:
  - docker
  
script:
  - docker build https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto/
  - docker build https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto-persistence/
  - 