language: node_js
os: linux
sudo: required
dist: trusty
node_js:
  - "7"
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.3/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
install:
- npm install --silent -g phantomjs 
- npm install --silent -g casperjs 
- npm install --silent -g slimerjs
- npm install --silent -g gl
- npm config set registry http://registry.npmjs.org/
- git clone https://github.com/openworm/org.geppetto.model.git -b $TRAVIS_BRANCH
- cd org.geppetto.model
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git -b $TRAVIS_BRANCH
- cd org.geppetto.core
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git -b $TRAVIS_BRANCH
- cd org.geppetto.simulation
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git -b $TRAVIS_BRANCH
- cd org.geppetto.model.neuroml
- mvn install
- cd ..
- wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.3/nrn-7.3.tar.gz
- tar xzvf nrn-7.3.tar.gz
- cd nrn-7.3
- ./configure --prefix `pwd` --without-iv --with-nrnpython
- make
- make install
- cd src/nrnpython
- sudo python setup.py install
- cd ..
- cd ..
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulator.external.git -b $TRAVIS_BRANCH
- cd org.geppetto.simulator.external
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.swc.git -b $TRAVIS_BRANCH
- cd org.geppetto.model.swc
- mvn install
- cd ..
- git clone https://github.com/openworm/org.geppetto.persistence.git -b $TRAVIS_BRANCH
- cd org.geppetto.persistence
- mvn install
- cd ..

services:
  - docker
addons:
  firefox: "51.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-51.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    
script:
  - npm config set registry http://registry.npmjs.org/
  - echo "Current time :$(date +"%T")"
  - cd $TRAVIS_BUILD_DIR/src/main/webapp/js/pages/tests/casperjs
  - echo "$TRAVIS_BRANCH"
  - docker build -t="geppetto" --build-arg frontendBranch=development https://github.com/openworm/org.geppetto.git#development:utilities/docker/geppetto/
  - echo "Current time :$(date +"%T")"
  - docker run  -t -dit --name=geppetto_container -h localhost -p  28081:8080 geppetto
  - bash $TRAVIS_BUILD_DIR/src/main/webapp/js/pages/tests/casperjs/utilities/test_geppetto_server.sh
  - sleep 30
  - http_status=$(curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
      echo "Restart run";
      echo "Printing logs for debugging purposes";
      sudo docker cp geppetto_container:/home/developer/virgo/serviceability/logs/log.log /etc
      tail /etc/log.log -n 200
      docker stop $(docker ps -a -q);
      docker rm $(docker ps -a -q);
      docker run  -t -dit --name=geppetto_container -h localhost -p  28081:8080 geppetto;
      bash $TRAVIS_BUILD_DIR/src/main/webapp/js/pages/tests/casperjs/utilities/test_geppetto_server.sh
      sleep 60;
      http_status=$(curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'});
      echo "Done restarting";
      echo "$http_status";
    done;
  - "curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'}"
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test --includes=utilities/TestsUtility.js UIComponentsTests.js --host=http://localhost:28081/ --engine=slimerjs  
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test --includes=utilities/TestsUtility.js GeppettoModelTests.js --host=http://localhost:28081/ --engine=slimerjs 
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test --includes=utilities/TestsUtility.js,NeuronalTestsLogic.js DefaultProjectsTests.js --host=http://localhost:28081/ --engine=slimerjs  
  - sudo docker cp geppetto_container:/home/developer/virgo/serviceability/logs/log.log /etc
  - tail /etc/log.log -n 200
  - echo "Current time :$(date +"%T")"
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - echo "$TRAVIS_BRANCH"
  - docker build -t="geppetto_persistence" --build-arg aKey=$accessKey --build-arg sKey=$secretKey https://github.com/openworm/org.geppetto.git#development:utilities/docker/geppetto-persistence/
  - echo "Current time :$(date +"%T")"
  - docker run  -t -dit --name=geppetto_persistence_container -h localhost -p 28081:8080 geppetto_persistence
  - bash utilities/test_geppetto_server.sh
  - sleep 30
  - http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'})
  - echo $http_status;
  - while [ "$http_status" == "404" ]; do
      echo "Restart run";
      docker stop $(docker ps -a -q);
      docker rm $(docker ps -a -q);
      docker run  -t -dit --name=geppetto_persistence_container -h localhost -p 28081:8080 geppetto_persistence;
      bash utilities/test_geppetto_server.sh;
      sleep 100;
      http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'});
      echo "Done restarting";
      echo "$http_status";
    done
  - sleep 30;
  - curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'}
  - echo "Current time :$(date +"%T")"
  - xvfb-run -a --server-args="-screen 0 1024x768x24" casperjs test --includes=PersistenceTestsLogic.js PersistenceTests.js --host=http://localhost:28081/ --engine=slimerjs
  - docker ps -a
  - echo "Current time :$(date +"%T")"
  - sudo docker cp geppetto_persistence_container:/home/developer/virgo/serviceability/logs/log.log /etc
  - tail /etc/log.log -n 100
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)