language: node_js
os: linux
sudo: required
dist: trusty
node_js:
  - "7"
install:
- git clone https://github.com/openworm/org.geppetto.frontend.git --quiet -b $TRAVIS_BRANCH
- cd org.geppetto.frontend
- cd ..
- npm install --silent -g phantomjs 
- npm install --silent -g casperjs 
- npm install --silent -g slimerjs
- npm install --silent -g gl

services:
  - docker
addons:
  firefox: "51.0"
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - export SLIMERJSLAUNCHER=/home/travis/firefox-51.0/firefox/firefox
  - export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/
    
script:
  - echo "$TRAVIS_BRANCH"
  - cd org.geppetto.frontend/src/main/webapp/js/pages/tests/casperjs
  - docker build -t="geppetto" --build-arg frontendBranch=development --build-arg persistenceBranch=development https://github.com/openworm/org.geppetto.git#docker-casperjs:utilities/docker/geppetto/
  - docker run  -t -dit --name=geppetto_container -h localhost -p  28081:8080 geppetto
  - docker ps -a
  - docker logs --details geppetto_container
  - sleep 120
  - http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'})
  - echo $http_status;
  - while [ "$http_status" == "404" ]; do
      echo "Restart run";
      docker stop $(docker ps -a -q);
      docker rm $(docker ps -a -q);
      docker run  -t -dit --name=geppetto_container -h localhost -p  28081:8080 geppetto;
      sleep 150;
      http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'});
    done
  - curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'}
  - xvfb-run -a --server-args="-screen 0 1024x768x24"  casperjs test --includes=CoreTestsUtility.js CoreTests.js --host=http://localhost:28081/ --engine=slimerjs
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
  - docker build -t="geppetto_persistence" --build-arg frontendBranch=development --build-arg persistenceBranch=development --build-arg aKey=$accessKey --build-arg sKey=$secretKey https://github.com/openworm/org.geppetto.git#development:utilities/docker/geppetto-persistence/
  - docker run  -t -dit --name=geppetto_persistence_container -h localhost -p 28081:8080 geppetto_persistence
  - sleep 120
  - http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
      echo "Restart run";
      docker stop $(docker ps -a -q);
      docker rm $(docker ps -a -q);
      docker run  -t -dit --name=geppetto_persistence_container -h localhost -p 28081:8080 geppetto_persistence;
      sleep 200;
      http_status=$(curl -s -I $1 http://localhost:28081 | grep HTTP/1.1 | awk {'print $2'});
    done
  - "curl -s -I $1 http://localhost:28081/org.geppetto.frontend | grep HTTP/1.1 | awk {'print $2'}"
  - xvfb-run -a --server-args="-screen 0 1024x768x24" casperjs test PersistenceTests.js --host=http://localhost:28081/ --engine=slimerjs
  - docker ps -a
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)