language: java
env:
  matrix:
  - NEURON_HOME=$TRAVIS_BUILD_DIR/nrn-7.3/x86_64/bin/
  global:
    secure: dn0FPQ5IG4M/3kdwnyI78ElQ308Vc3QnKAvkWfwMFb8QxDqxQdnTo7AV1qTMtbLrDNkeEWIgi4nc7jmXNtvGTwOfhAULVh6606Qs5B+ezTdwzajbbFMI8SKQx/pnTojOMu8dx7V4lMoR/YWcojR0VC1IWVC62TGbSB1k5BDGgH0=
install:
- git clone https://github.com/openworm/org.geppetto.model.git --quiet -b development
- cd org.geppetto.model
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.core.git --quiet -b development
- cd org.geppetto.core
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.simulation.git --quiet -b development
- cd org.geppetto.simulation
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.model.neuroml.git --quiet -b development
- cd org.geppetto.model.neuroml
- mvn --quiet -q install
- cd ..
- git clone https://github.com/openworm/org.geppetto.frontend.git -b development
- cd org.geppetto.frontend
- mvn --quiet -q install
- npm install --silent -g phantomjs npm install --silent -g casperjs
- sudo apt-get install -y xvfb libc6 libstdc++6 libgcc1 libgtk2.0-0 libasound2 libxrender1 libdbus-glib-1-2
sudo: required
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
services:
  - docker
  
addons:
  firefox: "51.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "curl https://slimerjs.org/slimerjs-pubkey.gpg | gpg --import"
  - "wget https://download.slimerjs.org/releases/0.10.3/slimerjs-0.10.3.tar.bz2"
  - "wget https://download.slimerjs.org/releases/0.10.3/slimerjs-0.10.3.tar.bz2.asc"
  - "gpg --verify-files *.asc"
  - "tar jxfv slimerjs-0.10.3.tar.bz2"
  - "mv slimerjs-0.10.3 ./slimerjs"
sudo: required
script:
  - cd ./slimerjs
  - ls -d
  - slimerjs --version
  - cd src/main/webapp/js/pages/tests/casperjs
  - xvfb-run -a ./slimerjs/slimerjs --debug=true CoreTests.js
  - casperjs test --includes=CoreTestsUtility.js CoreTests.js --engine=./slimerjs/slimerjs