# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name : Install Neuron
      run : |
        wget http://www.neuron.yale.edu/ftp/neuron/versions/v7.4/nrn-7.4.tar.gz
        tar xzvf nrn-7.4.tar.gz
        cd nrn-7.4
        ./configure --prefix `pwd` --without-iv --with-nrnpython
        make 
        make install
        cd src/nrnpython
        sudo python setup.py install
        cd ../../..

    - name : Install jNeuroML
      run : |
        svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar
        export JNML_HOME=$PWD/jNeuroMLJar
              
    - name: Install python-tk
      run: apt-get install python-tk
      
    - name: Install PIP Dependencies
      run: python -m pip install --upgrade pip netpyne numpy scipy lxml libneuroml pyneuroml matplotlib
    
    - name : Checkout org.geppetto.model
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.geppetto.model.git
        path : ./org.geppetto.model
        ref: development  
    - name : Build org.geppetto.model
      with:
        path : ./org.geppetto.model
      run : mvn -e clean install 
    
    - name : Checkout org.geppetto.core
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.geppetto.core.git
        path : ./org.geppetto.core
        ref: development
    - name : Build org.geppetto.core
      with:
        path : ./org.geppetto.core
      run : mvn -e clean install
    
    - name : Checkout org.geppetto.simulation
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.geppetto.simulation.git
        path : ./org.geppetto.simulation
        ref: development  
    - name : Build org.geppetto.simulation
      with:
        path : ./org.geppetto.simulation
      run : mvn -e clean install
    
    - name : Checkout org.geppetto.model.neuroml
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.geppetto.model.neuroml.git
        path : ./org.geppetto.model.neuroml
        ref: development 
    - name : Build org.geppetto.model.neuroml
      with:
        path : ./org.geppetto.model.neuroml
      run : mvn -e clean install
    
    - name : Checkout org.geppetto.simulator.external
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.simulator.external.git
        path : ./org.geppetto.simulator.external
        ref: development  
    - name : Build org.geppetto.simulator.external
      with:
        path : ./org.geppetto.simulator.external
      run : mvn -e clean install
    
    - name : Checkout org.geppetto.model.swc
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.model.swc.git
        path : ./org.geppetto.model.swc
        ref: development
    - name : Build org.geppetto.model.swc
      with:
        path : ./org.geppetto.model.swc
      run : mvn -e clean install
    
    - name : Checkout org.geppetto.persistence
      uses : actions/checkout@development
      with : 
        repository:  openworm/org.persistence.git
        path : ./org.geppetto.persistence
        ref: development  
    - name : Build org.geppetto.persistence
      with:
        path : ./org.geppetto.persistence
      run : mvn -e clean install
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -e clean install
