# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_BRANCH: ${{ github.head_ref }} 
      GIT_PULL_REQUEST: ${{ github.event.number }} 
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
        
    - name : Install Neuron
      run : |
        sudo apt-get install libx11-dev git bison flex automake libtool libxext-dev libncurses-dev python3-dev xfonts-100dpi cython3 libopenmpi-dev python3-scipy make zlib1g-dev
        wget https://neuron.yale.edu/ftp/neuron/versions/v7.7/nrn-7.7.tar.gz
        tar xzvf nrn-7.7.tar.gz
        cd nrn-7.7
        ./configure --prefix `pwd` --without-iv --with-nrnpython=python3
        make -j
        make install -j
        cd src/nrnpython
        sudo python3 setup.py install
        cd ../../..
        export NEURON_HOME=$PWD/nrn-7.7/x86_64/bin/

    - name : Install jNeuroML
      run : |
        svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar
        export JNML_HOME=$PWD/jNeuroMLJar
              
    - name: Install python-tk
      run: sudo apt-get install python-tk
      
    - name: Install PIP Dependencies
      run: python -m pip install --upgrade pip netpyne numpy scipy lxml libneuroml pyneuroml matplotlib
    
    - name : Checkout org.geppetto.model
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.model.git
        path : ./org.geppetto.model
        ref: $GIT_BRANCH  
    - name : Build org.geppetto.model
      run : |
        cd ./org.geppetto.model
        mvn -e clean install
        cd ..
        
    - name : Checkout org.geppetto.core
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.core.git
        path : ./org.geppetto.core
        ref: $GIT_BRANCH
    - name : Build org.geppetto.core
      run : |
        cd ./org.geppetto.core
        mvn -e clean install
        cd ..
    
    - name : Checkout org.geppetto.simulation
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.simulation.git
        path : ./org.geppetto.simulation
        ref: $GIT_BRANCH  
    - name : Build org.geppetto.simulation
      run : |
        cd ./org.geppetto.simulation
        mvn -e clean install
        cd ..
    
    - name : Checkout org.geppetto.model.neuroml
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.model.neuroml.git
        path : ./org.geppetto.model.neuroml
        ref: $GIT_BRANCH 
    - name : Build org.geppetto.model.neuroml
      run : |
        cd ./org.geppetto.model.neuroml
        mvn -e clean install
        cd ..
    
    - name : Checkout org.geppetto.simulator.external
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.simulator.external.git
        path : ./org.geppetto.simulator.external
        ref: $GIT_BRANCH  
    - name : Build org.geppetto.simulator.external
      run : |
        cd ./org.geppetto.simulator.external
        mvn -e clean install
        cd ..
    
    - name : Checkout org.geppetto.model.swc
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.model.swc.git
        path : ./org.geppetto.model.swc
        ref: $GIT_BRANCH
    - name : Build org.geppetto.model.swc
      run : |
        cd ./org.geppetto.model.swc
        mvn -e clean install
        cd ..
    
    - name : Checkout org.geppetto.persistence
      uses : actions/checkout@v2.3.4
      with : 
        repository:  openworm/org.geppetto.persistence.git
        path : ./org.geppetto.persistence
        ref: $GIT_BRANCH  
    - name : Build org.geppetto.persistence
      run : |
        cd ./org.geppetto.persistence
        mvn -e clean install
        cd ..
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn -e clean install
